"""Data model for trading signals generated by SMA crossover."""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class SignalType(str, Enum):
    """Type of trading signal."""

    BUY = "BUY"
    SELL = "SELL"


@dataclass(frozen=True, slots=True)
class Signal:
    """A trading signal generated by SMA crossover on candle close."""

    type: SignalType
    timestamp: datetime  # UTC, time of the candle that triggered it
    price: float  # Close price of the triggering candle
    sma_fast: float  # SMA(9) value at signal time
    sma_slow: float  # SMA(21) value at signal time
